============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 6 items

python_testcases/test_shunting_yard.py ..FFFF                            [100%]

=================================== FAILURES ===================================
__________________ test_shunting_yard[input_data2-expected2] ___________________

input_data = [[10, '-', 5, '-', 2]], expected = [10, 5, '-', 2, '-']

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_shunting_yard(input_data, expected):
>       assert shunting_yard(*input_data) == expected
E       AssertionError: assert [10, 5, 2] == [10, 5, '-', 2, '-']
E         
E         At index 2 diff: 2 != '-'
E         Right contains 2 more items, first extra item: 2
E         Use -v to get more diff

python_testcases/test_shunting_yard.py:15: AssertionError
__________________ test_shunting_yard[input_data3-expected3] ___________________

input_data = [[34, '-', 12, '/', 5]], expected = [34, 12, 5, '/', '-']

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_shunting_yard(input_data, expected):
>       assert shunting_yard(*input_data) == expected
E       AssertionError: assert [34, 12, 5] == [34, 12, 5, '/', '-']
E         
E         Right contains 2 more items, first extra item: '/'
E         Use -v to get more diff

python_testcases/test_shunting_yard.py:15: AssertionError
__________________ test_shunting_yard[input_data4-expected4] ___________________

input_data = [[4, '+', 9, '*', 9, '-', ...]]
expected = [4, 9, 9, '*', '+', 10, ...]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_shunting_yard(input_data, expected):
>       assert shunting_yard(*input_data) == expected
E       AssertionError: assert [4, 9, 9, 10, 13] == [4, 9, 9, '*', '+', 10, ...]
E         
E         At index 3 diff: 10 != '*'
E         Right contains 4 more items, first extra item: 10
E         Use -v to get more diff

python_testcases/test_shunting_yard.py:15: AssertionError
__________________ test_shunting_yard[input_data5-expected5] ___________________

input_data = [[7, '*', 43, '-', 7, '+', ...]]
expected = [7, 43, '*', 7, '-', 13, ...]

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_shunting_yard(input_data, expected):
>       assert shunting_yard(*input_data) == expected
E       AssertionError: assert [7, 43, 7, 13, 7] == [7, 43, '*', 7, '-', 13, ...]
E         
E         At index 2 diff: 7 != '*'
E         Right contains 4 more items, first extra item: 13
E         Use -v to get more diff

python_testcases/test_shunting_yard.py:15: AssertionError
=========================== short test summary info ============================
FAILED python_testcases/test_shunting_yard.py::test_shunting_yard[input_data2-expected2]
FAILED python_testcases/test_shunting_yard.py::test_shunting_yard[input_data3-expected3]
FAILED python_testcases/test_shunting_yard.py::test_shunting_yard[input_data4-expected4]
FAILED python_testcases/test_shunting_yard.py::test_shunting_yard[input_data5-expected5]
========================= 4 failed, 2 passed in 0.03s ==========================
